### ISSUE TITLE
--help fails

### ISSUE THREAD

**Issue by jayvdb** [moremoban/yehua#30]
Running `yh` without any args starts the project init process.

If I try `yh --help`, it fails.

```
yh --help
Traceback (most recent call last):
  File "/usr/bin/yh", line 11, in <module>
    load_entry_point('yehua==0.0.7', 'console_scripts', 'yh')()
  File "/usr/lib/python3.7/site-packages/yehua/main.py", line 40, in main
    project = Project(yehua_file)
  File "/usr/lib/python3.7/site-packages/yehua/project.py", line 13, in __init__
    raise Exception("%s does not exist" % yehua_file)
Exception: --help does not exist
```

**Comment by chfw** [comment]
OK. I will have a look.
