### ISSUE TITLE
show stopper: simple 'yh' failed to create a project

### ISSUE THREAD

**Issue by chfw** [moremoban/yehua#63]
due to missing cookiecutter as dependency

**Comment by chfw** [comment]
```
Yehua /'jɛhwa/ will walk you through creating a blank python package.
Press ^C to quit at any time.

project name [yehua-boilerplate]: moban-anyconfig
description [Moremoban organisation's best template]: Take any config as moban data for rendering
license: 
[✓] 1. mit
[ ] 2. newbsd
author: C.W.
contact email: wangc_2011@hotmail.com
github profile/organisation: moremoban
copyright owner [C.W.]: moban dev team
project type: 
[✓] 1. library
[ ] 2. command line interface
Traceback (most recent call last):
  File "/Users/jaska/github/moremoban/moban/moban/externals/file_system.py", line 37, in wrapper
    return function_in_this_module(*args, **kwds)
  File "/Users/jaska/github/moremoban/moban/moban/externals/file_system.py", line 103, in read_unicode
    with open_file(path) as file_handle:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/jaska/github/moremoban/moban/moban/externals/file_system.py", line 73, in open_file
    the_fs = fs.open_fs(dir_name)
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/fs/opener/registry.py", line 226, in open_fs
    default_protocol=default_protocol,
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/fs/opener/registry.py", line 187, in open
    open_fs = opener.open_fs(fs_url, parse_result, writeable, create, cwd)
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/fs/opener/osfs.py", line 41, in open_fs
    osfs = OSFS(path, create=create)
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/fs/osfs.py", line 140, in __init__
    raise errors.CreateFailed(message)
fs.errors.CreateFailed: root path '/Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/yehua/resources/yehua.yml' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/yehua/main.py", line 53, in main
    yehua = cookiecutter_json_to_yehua_file(yehua_file)
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/yehua/cookiecutter_to_yehua.py", line 17, in cookiecutter_json_to_yehua_file
    content = read_unicode(url_join(path, "cookiecutter.json"))
  File "/Users/jaska/github/moremoban/moban/moban/externals/file_system.py", line 41, in wrapper
    raise exceptions.FileNotFound(args[0])
moban.exceptions.FileNotFound: /Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/yehua/resources/yehua.yml/cookiecutter.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jaska/github/moremoban/moban-env/bin/yh", line 8, in <module>
    sys.exit(main())
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/yehua/main.py", line 57, in main
    project = Project(yehua_file)
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/yehua/project.py", line 27, in __init__
    self._append_magic_variables()
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/yehua/project.py", line 114, in _append_magic_variables
    self.jj2_environment = self._create_jj2_environment(self.template_dir)
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/yehua/project.py", line 138, in _create_jj2_environment
    extensions=default_extensions,
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/jinja2/environment.py", line 333, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/jinja2/environment.py", line 85, in load_extensions
    extension = import_string(extension)
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.7/site-packages/jinja2/utils.py", line 143, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
ModuleNotFoundError: No module named 'cookiecutter'
```
